export const FILMS_REQUESTED = 'FILMS_REQUESTED';
export const FILMS_LOADED = 'FILMS_LOADED';
export const API_ERRORED = 'API_ERRORED';
export const FILM_REQUESTED = 'FILM_REQUESTED';
export const FILM_LOADED = 'FILM_LOADED';